[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[edge_functions]]
function = "inngest"
path = "/api/inngest"

[[edge_functions]]
function = "chat"
path = "/api/chat"

[[edge_functions]]
function = "checkout"
path = "/api/checkout"

[[edge_functions]]
function = "webhook"
path = "/api/webhook"

[[edge_functions]]
function = "trigger"
path = "/api/trigger"